name: Update README with Solved Counts

on:
  push:
    branches:
      - master  # Run on pushes to main branch
  schedule:
    - cron: "0 0 * * *"  # Optionally run daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Run count_solutions.py
      run: python .github/scripts/count_solutions.py

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add README.md
        git commit -m "Update solved problem counts in README"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
